### ISSUE TITLE
AVRO support 

### ISSUE THREAD

**Issue by akhil29sep** [carlomedas/4mc#1]
Hi
Couple of doubts
1. How to convert text file to 4mc file format in linux so that it can be used as input to my mapreduce program.
2. Can 4mc commpression used on AVRO file format..?

Thanks

Kind Regards
Akhil Dogra

**Comment by carlomedas** [comment]
1. once you build 4mc it provides the command line '4mc' tool that can compress/uncompress ; if you have doubts or issues building, let me know
2. 4mc is a container, so it can contain anything; if you want to use it with hadoop leveraging scalability, an adapter must be created; e.g. if ElephantBird supports it, I can help you create the bridge between the two.

**Comment by akhil29sep** [comment]
Thanks : ) , I will try doing what you suggested and will post if i stucks somewhere.

Akhil

**Comment by carlomedas** [comment]
Most welcome, let me know.
