### ISSUE TITLE
Can not specify output file/folder name using command line tool (darwin)

### ISSUE THREAD

**Issue by baaa** [carlomedas/4mc#19]
These commands are executed back to back on the same input file, it only works when I do not specify any output file at all

<pre>UK-HAV-M4NAG8WN:zstd-fast yucelm01$ 4mc -d split_0000.4mz /tmp/delete/split_0000.json
Unrecognized header : not a 4mc file
UK-HAV-M4NAG8WN:zstd-fast yucelm01$ 4mc -d split_0000.4mz /tmp/delete/split_0000
Unrecognized header : not a 4mc file
UK-HAV-M4NAG8WN:zstd-fast yucelm01$ 4mc -d split_0000.4mz /tmp/delete/split_0000.4mc
Unrecognized header : not a 4mc file
UK-HAV-M4NAG8WN:zstd-fast yucelm01$ 4mc -d split_0000.4mz /tmp/delete
Warning : /tmp/delete already exists
Overwrite ? (Y/N) : y
Cannot open output file: /tmp/delete
UK-HAV-M4NAG8WN:zstd-fast yucelm01$ 4mc -d split_0000.4mz
Decoding file split_0000 
Compression: ZSTD
Successfully decoded 32517745 bytes                                            
UK-HAV-M4NAG8WN:zstd-fast yucelm01$</pre>

edit:
also it fails with the same error if I have a dot(.) in the filename anywhere like:
`4mc -d split_0000.json.4mz`

**Comment by carlomedas** [comment]
what if you do -z -d ?

**Comment by baaa** [comment]
both `4mc -z -d split_0000.4mz /tmp/delete/split_0000.json` and `4mc -z -d split_0000.json.4mz /tmp/delete/split_0000.json` works.

it even works without any extension at all (as it should) I guess the only trick is gotto know the compression type and provide -z flag, cheeers. I guess I will need to read the header and decide.

**Comment by carlomedas** [comment]
yes, it was implemented like that atm. it's not reading the header to understand the type.
feel free to implement it and pull request, thanks in advance!
