### ISSUE TITLE
What is the idea behind design of footer?

### ISSUE THREAD

**Issue by tesseract2048** [carlomedas/4mc#5]
I've noticed that, to make stream splittable, we have to read footer section to determine block indexes.
But in some context, it is hard to retrieve the file length, thus cannot easily seek to a relative position of the end of file.
On the other hand, in these contexts, another field in HEADER which indicates the footer offset will be handy.

Can this be solved?

**Comment by tesseract2048** [comment]
I've noticed that, to make stream splittable, we have to read footer section to determine block indexes.
But in some context, it is hard to retrieve the file length, thus cannot easily seek to a relative position of the end of file.
On the other hand, in these contexts, another field in HEADER which indicates the footer offset will be handy.

Can this be solved?

**Comment by carlomedas** [comment]
4mc was born for hadoop and similar distributed filesystems, where we have 2 main constraints:
- files must be written progressively, only once, without 'write then edit' easy capability
- retrieving file size is O(1) because it's meta data on namenode
